/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MockChainlinkInterface extends ethers.utils.Interface {
  functions: {
    "getPrice(address)": FunctionFragment;
    "setMarketPrice(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getPrice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMarketPrice",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMarketPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export class MockChainlink extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MockChainlinkInterface;

  functions: {
    getPrice(feed: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getPrice(address)"(
      feed: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setMarketPrice(
      feed: string,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMarketPrice(address,uint256)"(
      feed: string,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getPrice(feed: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getPrice(address)"(
    feed: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setMarketPrice(
    feed: string,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMarketPrice(address,uint256)"(
    feed: string,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getPrice(feed: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getPrice(address)"(
      feed: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setMarketPrice(
      feed: string,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMarketPrice(address,uint256)"(
      feed: string,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getPrice(feed: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getPrice(address)"(
      feed: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setMarketPrice(
      feed: string,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setMarketPrice(address,uint256)"(
      feed: string,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPrice(
      feed: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPrice(address)"(
      feed: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setMarketPrice(
      feed: string,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMarketPrice(address,uint256)"(
      feed: string,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
